# Generated by Django 4.2.3 on 2023-07-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('building_type', models.CharField(max_length=100)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contact', models.CharField(max_length=100)),
                ('ansidd_no', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='building/images/')),
            ],
        ),
    ]
