# Generated by Django 3.2.20 on 2023-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='geographical_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
