# Generated by Django 3.2.20 on 2023-07-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_geographical_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='contact',
        ),
    ]
