# Generated by Django 3.2.20 on 2023-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20230707_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
